Adding .github and updating repo readme
applicaster/zapp-plugins-examples pull request #22
Opened 2019-04-30 12:05 UTC by lomudi

Adding `.github` with issues and PR templates.
Updating the `README.md`.

2019-04-30 20:15 UTC, liviur commented on README.md
> +* [iOS example](./LoginPlugin/iOS)
Please add link to the docs:
https://developer-zapp.applicaster.com/login/intro.html

2019-04-30 20:16 UTC, liviur commented
@lomudi - please see my comment - you can merge after adding the link.
docs are for both platforms

2019-05-01 07:43 UTC, guysarfatty requested changes

2019-05-01 07:43 UTC, guysarfatty commented on README.md
>  This repostory contains few `Zapp Plugins` examples that will help you to get started with creating different types of plugins for Zapp.
a few

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +If you are new with developing plugins for Applicaster Zapp platform, you start with the [Getting Started Guide](https://developer-zapp.applicaster.com/getting-started/zapp-plugins.html).
new to developing

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an Andorid and iOS projects that present the implementation of the `Zapp pluggable player API`.
includes

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an Andorid and iOS projects that present the implementation of the `Zapp pluggable player API`.
remove the "an"

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an Andorid and iOS projects that present the implementation of display advertisement plugin.
includes

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an Andorid and iOS projects that present the implementation of display advertisement plugin.
remove the "an"

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an Andorid and iOS projects that present the implementation of an analytics plugin.
includes + remove the "an"

2019-05-01 07:43 UTC, guysarfatty commented on README.md
> +This example include an iOS project that present the implementation of an login plugin.
includes 
presents

2019-05-01 07:54 UTC, guysarfatty approved these changes

2019-05-01 07:55 UTC, merged